language: node_js

node_js:
- node

script:
    - npm install -g snyk
    # - snyk monitor --all-projects --remote-repo-url=goof-github-travisci
    - snyk monitor --project-name=goof-travisci --remote-repo-url=goof-travisci
